server:
  #port: 8080 # 应用程序运行端口
  #https默认端口：443，http默认端口：80
  port: 443

  ssl:
    enabled: true
    key-store: classpath:alic_https_rsa.keystore  # 证书文件路径
    key-store-password: 123456   # 证书密码
    key-store-type: PKCS12
    enabled-protocols: TLSv1.2,TLSv1.3


logging:
  level:
    com.example.mapper: debug
jwt:
  config:
    key: alic_salt_1q2w3e4R!@#$
    expire: 14400 # 过期时间，单位秒, 4小时
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/alic?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: 1q2w3e4R
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    type-aliases-package: com.eduhk.alic.alicbackend.model.entity
    mapper-locations: com.eduhk.alic.alicbackend.dao
    configuration:
      ### 开启打印sql配置
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      ### 开启驼峰配置
      map-underscore-to-camel-case: true
      useGeneratedKeys: true
  mail:
    #默认的邮件编码
    default-encoding: UTF-8
    # 设置邮箱主机(服务商),这里使用QQ邮件服务器 ---->配置 SMTP 服务器地址
    host: smtp.163.com
    #配置邮箱用户名
    username: alic_admin@163.com
    #配置密码，注意，不是真正的密码，而是刚刚申请到的授权码
    password: PQc6NjriYvubLeG6
    #SMTP 服务器的端口
    port: 587
    properties:
      mail:
        smtp:
          # 必须进行授权认证，它的目的就是阻止他人任意乱发邮件
          auth: true
          #SMTP加密方式:连接到一个TLS保护连接
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms